### PR TITLE
Threadio tests

### PR DESCRIPTION
**Pull request by coreyjadams**
As seen in the final commit, this adds a suite of tests for the entire threadio and larcv_interface package.  There are not tests yet for distributed IO since that requires a testing suite that has MPI capability.

### CODE REVIEW

**Comment by marcodeltutto** [comment]
The Travis CI test has failed, although I cannot reproduce the problem if I run the tests locally.

**Comment by coreyjadams** [comment]
I also see this behavior.  Travis runs Ubuntu so I will try to see this on linux, particularly ubuntu.

**Comment by coreyjadams** [comment]
It looks like this is due to oversubscribing, somehow, the available number of threads on a system.  I can reproduce this behavior on a linux system.  If I turn down the number of tests that run at once, it succeeds.  If I run the unmodified threadIO tests, it fails.  But if I rerun only failed tests (`py.test --lf .`) it will succeed in the first half dozen tests, then start failing.

It's not a realistic situation to be running this many threads at once (N + 1 per test, where N == num threads, + python, + who knows what else).  A better implementation will serialize these tests.  I'll work on that.

**Comment by coreyjadams** [comment]
It appears there was a race condition introduced when running tests, as many threads were spawned simultaneously.  This was impossible to reproduce on mac, only linux, and didn't occur when running a single instance of a test function.

In the end, the spawning of the ThreadIO master thread was not checked for completion/thread starting before trying to use properties it set, which lead to a crash downstream in cases where that thread did not start fast enough.  Adding a wait in dataloader2 to check that the manager thread is running before returning from the python thread appears to solve this problem and all tests are passing.

**Review by marcodeltutto — APPROVED** [review]
All looks good to me. I have run it on a my Mac and all tests pass. Also the Travis ones pass now.

**Pull request merged**
