### PR TITLE
Distributed io allranks

### PR DESCRIPTION
**Pull request by marcodeltutto**
This branch includes changes that allow running ThreadProcessor on several MPI processes reading different entries in the file. The start entry can now be specified explicitly, and also how many entries have to be skipped between two consecutive readings.

The distributed_larcv_interface now allows the option "read_from_all_ranks" in the constructor. If this is set to true, an instance of larcv_threadio (and so of ThreadProcessor) will be present in all ranks. The start entry of every rank is set to (rank * minibatch_size), and the number of entries to skip between to readings is set to (size * minibatch_size), where rank is the rank number, and size is the number of ranks.

### CODE REVIEW

**Comment by marcodeltutto** [comment]
The distributed_larcv_interface now has 3 options to read the data: 
1. Can read  from only one rank and distribute to all the other ranks;
2. Can read from one local rank, and then distribute to all other ranks in the same node;
3. Can read from all ranks, and no distribution is needed.

This option can be specified in the distributed_larcv_interface constructor:
1. "read_from_single_rank"
2. "read_from_single_local_rank"
3. "read_from_all_ranks"

**Review by coreyjadams — COMMENTED** [review]
This looks great.  I am approving this now, but I am would like to merge in the threadIO test suite first to this branch and make sure all tests pass.  So, the proposal is:
 - Review and merge the pull request #21 for thread IO tests
 - Merge develop into this branch to let the CI run the thread IO tests on these changes.
 - If everything passes, we merge today.

I am going to leave the branch open for future developments in distributed IO:
 - Extending the local-IO capabilities beyond single host, so that one node could do IO for several nodes.  This is useful in a system unable to handle many simultaneous IO access, but in a project needing more than one IO worker.  I think this is a short step further in this workflow.
- Add larcv_interface that works from IOManager directly but uses MPI-IO within IO Manager.  This would allow every process to do it's own IO, from a single file.  This will require some integration to coordinate batch index.  There may be a danger using the current data loader setup, particularly with more than 1 thread, 1 batch storage.  Each MPI-IO call is a collective operation and all processes need to enter/exit them together.

**Comment by coreyjadams** [comment]
I have updated this branch with the threadio tests and hdf5-fix branch, if all tests pass I will merge.

**Comment by coreyjadams** [comment]
All tests have passed.  I am going to merge into develop.

It should be noted that there are not tests available yet for the distributed IO interface.  I will open an issue to work on this.

**Review by coreyjadams — APPROVED** [review]

**Pull request merged**
